DROP TABLE "@SCHEMA@"."ODBC_FDW_BULK" PURGE;

CREATE TABLE "@SCHEMA@"."ODBC_FDW_BULK" (
    "ID"    NUMBER(10, 0) PRIMARY KEY,
    "LABEL" VARCHAR2(32)
);

INSERT INTO "@SCHEMA@"."ODBC_FDW_BULK"
SELECT LEVEL, 'row-' || TO_CHAR(LEVEL)
FROM DUAL
CONNECT BY LEVEL <= @ROWS@;

COMMIT;
