DROP TABLE "@SCHEMA@"."ODBC_FDW_DATA_TYPES";
DROP TABLE "@SCHEMA@"."ODBC_FDW_LARGE_VALUES";
DROP TABLE "@SCHEMA@"."ODBC_FDW_SINGLE_ROW";
DROP TABLE "@SCHEMA@"."ODBC_FDW_TYPE_MATRIX";
DROP TABLE "@SCHEMA@"."ODBC_FDW_ENCODING_MATRIX";
DROP TABLE "@SCHEMA@"."ODBC_FDW_JSON_VALUES";
DROP TABLE "@SCHEMA@"."odbc_fdw_lower_table";
DROP TABLE "@SCHEMA@"."OdbcFdwMixedTable";
