DROP TABLE IF EXISTS ODBC_FDW_DATA_TYPES;
DROP TABLE IF EXISTS ODBC_FDW_TYPE_MATRIX;
DROP TABLE IF EXISTS ODBC_FDW_LARGE_VALUES;
DROP TABLE IF EXISTS ODBC_FDW_SINGLE_ROW;
DROP TABLE IF EXISTS ODBC_FDW_JSON_VALUES;
DROP TABLE IF EXISTS "odbc_fdw_lower_table";
DROP TABLE IF EXISTS "OdbcFdwMixedTable";

CREATE TABLE ODBC_FDW_DATA_TYPES (
    ID INTEGER PRIMARY KEY,
    TEXT_VALUE TEXT,
    INTEGER_VALUE INTEGER,
    DECIMAL_VALUE NUMERIC,
    DATE_VALUE DATE,
    TIME_VALUE TIME,
    TIMESTAMP_VALUE TIMESTAMP,
    NULL_VALUE TEXT,
    UNICODE_VALUE TEXT
);
INSERT INTO ODBC_FDW_DATA_TYPES VALUES
    (1, 'alpha', 42, 123.4500, '2024-01-02', '03:04:05',
     '2024-01-02 03:04:05', NULL, 'Grüße'),
    (2, 'beta', -7, -0.0100, '2024-12-31', '23:59:59',
     '2024-12-31 23:59:59', 'present', '東京');

CREATE TABLE ODBC_FDW_TYPE_MATRIX (
    ID INTEGER PRIMARY KEY,
    TINY_VALUE TINYINT,
    SMALL_VALUE SMALLINT,
    INTEGER_VALUE INTEGER,
    BIGINT_VALUE BIGINT,
    DECIMAL_VALUE NUMERIC,
    REAL_VALUE REAL,
    DOUBLE_VALUE DOUBLE,
    BOOLEAN_VALUE BOOLEAN,
    CHAR_VALUE CHAR(6),
    VARCHAR_VALUE VARCHAR(100),
    TEXT_VALUE TEXT,
    DATE_VALUE DATE,
    TIME_VALUE TIME,
    TIMESTAMP_VALUE TIMESTAMP,
    BLOB_VALUE BLOB
);
INSERT INTO ODBC_FDW_TYPE_MATRIX VALUES
    (1, 127, -32768, 2147483647, 922337203685477580,
     12345.6789, 3.25, 1234567.125, 1,
     'abc', 'Grüße 東京', 'plain text', '2024-06-30', '12:34:56',
     '2024-06-30 12:34:56', X'00FF1020');
INSERT INTO ODBC_FDW_TYPE_MATRIX VALUES
    (2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
     NULL, NULL, NULL, NULL, NULL, NULL, NULL);

CREATE TABLE ODBC_FDW_LARGE_VALUES (
    ID INTEGER PRIMARY KEY,
    TEXT_VALUE TEXT,
    BLOB_VALUE BLOB
);
INSERT INTO ODBC_FDW_LARGE_VALUES
SELECT 1, printf('%.*c', 6000, 'x'), X'004142FF';

CREATE TABLE ODBC_FDW_SINGLE_ROW (ID INTEGER PRIMARY KEY, PAYLOAD TEXT);
INSERT INTO ODBC_FDW_SINGLE_ROW VALUES (1, 'rescan');

CREATE TABLE ODBC_FDW_JSON_VALUES (ID INTEGER PRIMARY KEY, JSON_VALUE TEXT);
INSERT INTO ODBC_FDW_JSON_VALUES VALUES
    (1, '{"owner":"София","tags":["odbc","東京","😀"]}'),
    (2, NULL);

CREATE TABLE "odbc_fdw_lower_table" (
    "UPPER_VALUE" INTEGER, "lower_value" TEXT, "MixedValue" TEXT, "Spaced Value" TEXT
);
INSERT INTO "odbc_fdw_lower_table" VALUES
    (1, 'lower column', 'mixed column', 'space column');
CREATE TABLE "OdbcFdwMixedTable" (
    "UPPER_VALUE" INTEGER, "lower_value" TEXT, "MixedValue" TEXT, "Spaced Value" TEXT
);
INSERT INTO "OdbcFdwMixedTable" VALUES
    (2, 'lower mixed table', 'mixed mixed table', 'space mixed table');
