DROP TABLE IF EXISTS ODBC_FDW_DATA_TYPES;
DROP TABLE IF EXISTS ODBC_FDW_TYPE_MATRIX;
DROP TABLE IF EXISTS ODBC_FDW_LARGE_VALUES;
DROP TABLE IF EXISTS ODBC_FDW_SINGLE_ROW;
DROP TABLE IF EXISTS ODBC_FDW_JSON_VALUES;
DROP TABLE IF EXISTS `odbc_fdw_lower_table`;
DROP TABLE IF EXISTS `OdbcFdwMixedTable`;

CREATE TABLE ODBC_FDW_DATA_TYPES (
    ID INT PRIMARY KEY,
    TEXT_VALUE VARCHAR(100),
    INTEGER_VALUE INT,
    DECIMAL_VALUE DECIMAL(20,4),
    DATE_VALUE DATE,
    TIME_VALUE TIME(6),
    TIMESTAMP_VALUE DATETIME(6),
    NULL_VALUE VARCHAR(10),
    UNICODE_VALUE VARCHAR(100)
) CHARACTER SET utf8mb4;
INSERT INTO ODBC_FDW_DATA_TYPES VALUES
    (1, 'alpha', 42, 123.4500, '2024-01-02', '03:04:05.123456',
     '2024-01-02 03:04:05.123456', NULL, 'Grüße'),
    (2, 'beta', -7, -0.0100, '2024-12-31', '23:59:59.654321',
     '2024-12-31 23:59:59.654321', 'present', '東京');

CREATE TABLE ODBC_FDW_TYPE_MATRIX (
    ID INT PRIMARY KEY,
    TINY_VALUE TINYINT,
    UNSIGNED_TINY_VALUE TINYINT UNSIGNED,
    SMALL_VALUE SMALLINT,
    INTEGER_VALUE INT,
    BIGINT_VALUE BIGINT,
    DECIMAL_VALUE DECIMAL(18,4),
    FLOAT_VALUE FLOAT,
    DOUBLE_VALUE DOUBLE,
    BOOLEAN_VALUE BOOLEAN,
    BIT_VALUE BIT(1),
    CHAR_VALUE CHAR(6),
    VARCHAR_VALUE VARCHAR(100),
    TEXT_VALUE TEXT,
    LONGTEXT_VALUE LONGTEXT,
    DATE_VALUE DATE,
    TIME_VALUE TIME(6),
    DATETIME_VALUE DATETIME(6),
    TIMESTAMP_VALUE TIMESTAMP(6) NULL,
    YEAR_VALUE YEAR,
    BINARY_VALUE BINARY(4),
    VARBINARY_VALUE VARBINARY(4),
    BLOB_VALUE BLOB,
    LONGBLOB_VALUE LONGBLOB
) CHARACTER SET utf8mb4;
INSERT INTO ODBC_FDW_TYPE_MATRIX VALUES
    (1, 127, 255, -32768, 2147483647, 922337203685477580,
     12345678901234.5678, 3.25, 1234567.125, TRUE, b'1',
     'abc', 'Grüße 東京', 'plain text', 'long unicode Привет 東京',
     '2024-06-30', '12:34:56.123456', '2024-06-30 12:34:56.123456',
     '2024-06-30 12:34:56.123456', 2024,
     X'ABCD', X'1020', X'00FF1020', X'004142FF');
INSERT INTO ODBC_FDW_TYPE_MATRIX VALUES
    (2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
     NULL, NULL, NULL, NULL);

CREATE TABLE ODBC_FDW_LARGE_VALUES (
    ID INT PRIMARY KEY,
    TEXT_VALUE LONGTEXT,
    BLOB_VALUE LONGBLOB
) CHARACTER SET utf8mb4;
INSERT INTO ODBC_FDW_LARGE_VALUES VALUES
    (1, REPEAT('x', 6000), X'004142FF');

CREATE TABLE ODBC_FDW_SINGLE_ROW (ID INT PRIMARY KEY, PAYLOAD VARCHAR(100));
INSERT INTO ODBC_FDW_SINGLE_ROW VALUES (1, 'rescan');

CREATE TABLE ODBC_FDW_JSON_VALUES (ID INT PRIMARY KEY, JSON_VALUE JSON);
INSERT INTO ODBC_FDW_JSON_VALUES VALUES
    (1, '{"owner":"София","tags":["odbc","東京","😀"]}'),
    (2, NULL);

CREATE TABLE `odbc_fdw_lower_table` (
    `UPPER_VALUE` INT, `lower_value` VARCHAR(100),
    `MixedValue` VARCHAR(100), `Spaced Value` VARCHAR(100)
) CHARACTER SET utf8mb4;
INSERT INTO `odbc_fdw_lower_table` VALUES
    (1, 'lower column', 'mixed column', 'space column');
CREATE TABLE `OdbcFdwMixedTable` (
    `UPPER_VALUE` INT, `lower_value` VARCHAR(100),
    `MixedValue` VARCHAR(100), `Spaced Value` VARCHAR(100)
) CHARACTER SET utf8mb4;
INSERT INTO `OdbcFdwMixedTable` VALUES
    (2, 'lower mixed table', 'mixed mixed table', 'space mixed table');
